# Generated by Django 3.2.12 on 2022-03-09 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tourBusCore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalLicence', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalOwner', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalEngineNumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalBodyNumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalLicenceImage', models.ImageField(blank=True, null=True, upload_to=tourBusCore.models.image_upload_handler)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TourBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('county', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicalSeats', models.IntegerField(default=0)),
                ('vehicalLicence', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalOwner', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalEngineNumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalBodyNumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicalLicenceImage', models.ImageField(blank=True, null=True, upload_to=tourBusCore.models.image_upload_handler)),
                ('isPublish', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourBusRentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('startDate', models.DateTimeField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('tourBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourBusCore.tourbus')),
            ],
        ),
        migrations.CreateModel(
            name='TourBusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tourBusCore.models.image_upload_handler)),
                ('tourBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourBusCore.tourbus')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('startDate', models.DateTimeField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('depatureCity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('destinationCity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tourBus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tourBusCore.tourbus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourBusCore.city')),
            ],
        ),
        migrations.CreateModel(
            name='AnnounceMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announceDateTime', models.DateTimeField(null=True)),
                ('numbersOfPeople', models.IntegerField(default=0)),
                ('startDateTime', models.DateTimeField(null=True)),
                ('endDateTime', models.DateTimeField(null=True)),
                ('depatureCity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('destinationCity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('memo', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
