# Generated by Django 3.2.12 on 2022-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
