# Generated by Django 3.2.12 on 2022-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0002_user_line_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
