# Generated by Django 3.2.12 on 2022-04-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0003_smsverifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverifycode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='smsverifycode',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
