# Generated by Django 3.2.12 on 2022-04-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0005_auto_20220408_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbus',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tourbus',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
