# Generated by Django 3.2.12 on 2022-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0009_auto_20220416_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
