# Generated by Django 3.2.12 on 2022-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0011_alter_announcement_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbus',
            name='isTop',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
