# Generated by Django 3.2.12 on 2022-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0012_tourbus_istop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
    ]
