# Generated by Django 3.2.12 on 2022-04-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0014_alter_order_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ATMInfoBankCode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ATMInfoExpireDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ATMInfovAccount',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isAtm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
