# Generated by Django 3.2.12 on 2022-04-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0015_auto_20220422_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbus',
            name='vehicalBodyNumber',
        ),
        migrations.RemoveField(
            model_name='tourbus',
            name='vehicalEngineNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicalBodyNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicalEngineNumber',
        ),
    ]
