# Generated by Django 3.2.12 on 2022-04-30 02:13

from django.db import migrations, models
import tourBusCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0016_auto_20220429_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbus',
            name='driverLicenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=tourBusCore.models.image_upload_handler),
        ),
        migrations.AddField(
            model_name='user',
            name='driverLicenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=tourBusCore.models.image_upload_handler),
        ),
    ]
