# Generated by Django 3.2.12 on 2022-05-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0017_auto_20220430_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPassed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
