# Generated by Django 3.2.12 on 2022-05-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0019_auto_20220505_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
