# Generated by Django 3.2.12 on 2022-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBusCore', '0020_user_apple_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ATMFiveDigit',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
